#ENC[AES256_GCM,data:0k8wt4y6y5iuMSv81ybv7hSp8DE=,iv:myVT7CbHJesvVi1kO5q/8olvi87Dn6Dx6V0kjfwlsw4=,tag:sJ5rFz7xOo3oikAEm9c62w==,type:comment]
profile_tomcat::session_secret: ENC[AES256_GCM,data:nlKXLL/NVp1PeBtA8X0ea6DOfh/5Bb4RaA==,iv:pvDLf/XyyF5CdXRU95mCJA2aEd5mH8DEuQFq9/qnUeU=,tag:biCPlbyV9H2oTMCmLrLrEw==,type:str]
profile_tomcat::datasource_config:
    username: ENC[AES256_GCM,data:yRRsBSp6,iv:BVH3VpqqCf+tIkhyUW4YzxRyAvb4mgES+M4GWe7COcA=,tag:mPS6/6q/D6oAH0UKj/Fa3w==,type:str]
    password: ENC[AES256_GCM,data:VS2W1CmY+/MktdYQ6w==,iv:DiMUufNGa/z/fooxNCrZ9wWYJN5qy9M3kcPmyU/MFsE=,tag:EkA8r03oJBDCv+RvZeRdLQ==,type:str]
    validation_query: ENC[AES256_GCM,data:BAQDRlMa4tg=,iv:wgJjaxVdOpu4h1Ct9nV9XxStsJjel0LVqMkZjbOPKLc=,tag:QI+N2gmJKtrtoXJ2gwkesw==,type:str]
    max_active: ENC[AES256_GCM,data:5bo=,iv:B79McsbGfXjaZhL2+oEXkOZs+6vQy8EKRqAvVAQhLUI=,tag:xyDXtt5gWCPErQSvbAMCiw==,type:int]
    max_idle: ENC[AES256_GCM,data:2IE=,iv:jnqjOA7LXzKM2BtNVbUmIPEVd0WfECbm1yj5b4aG8Ew=,tag:9vVByGT3vAM8XMe2hG6ubA==,type:int]
    min_idle: ENC[AES256_GCM,data:Yw==,iv:0g4GTlIJj/KNmTvkPQ9Id9Dp1cUXns16pOeac9tPMQI=,tag:N4N9o80kWLa9j0ahuzvxug==,type:int]
sops:
    age:
        - recipient: age177f2346qq7z8e5cwr9qve2z0fh0dhw4z2w7pevrq0xt88enfvqlqe8jate
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBya0dZZ1l0UWtaeGk1anhZ
            K01CaitkcFFCb2pwcTA5eU9CN2ZHaE1sMFFRClptbmMwOWk5UENuNis2NUNkWVRa
            ZHZ3V0JRSGdLVHZtY2ltakNFTG9NSHcKLS0tICtuTlFsUGx4aEZtaTdndDh0aEFH
            RHNGeWovc3JKSEJ4RUVoUmpVVHU0SUUK0gaC1gnbruC4uS5o3b3O2aVkKUvxoXlC
            COnL8JAwaN/K4Xoa2WYcjv4KP6yZkIgzNL0Nz5TkI+pOU0j2B3RhgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T08:20:08Z"
    mac: ENC[AES256_GCM,data:rxwytSpqjc1rtVXG09kCZ7w0neY918eRD1Ja28/Znm9HGvbRW5dA0qzIxpGHjYI45+jqS80Nad+cot8W5/mB0zSWxoBl82Nwe0uRqj52u2o8wApw7Qfc956THhfFiuj5kgRO6OX0k9xId0S7oqEs7Rs8bIkjhKz2daYhgQoIE9s=,iv:8vcA+s+Vjn/L3uErc9N5QzErhQyntMQQefywWXR2mK8=,tag:INnHvzTYrgdU3i05SagHHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
